# Generated by Django 2.1.5 on 2019-02-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190209_0514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomProfile',
        ),
    ]
