# Generated by Django 2.1.5 on 2019-02-10 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_randomprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='owner',
        ),
    ]
