# Generated by Django 2.2 on 2019-04-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parameter', models.TextField(blank=True, max_length=500)),
                ('value', models.TextField(blank=True, max_length=200)),
                ('optional_extra', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
